[workspace]
members = ["libphile", "philec"]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"

[profile.bench]
panic = "abort"

[profile.doc]
panic = "abort"

[profile.test]
panic = "unwind"
