[package]
name          = "phile"
version       = "0.1.0"
authors       = ["Árpád Goretity <h2co3@h2co3.org>"]
repository    = "https://github.com/H2CO3/PHiLe.git"
homepage      = "http://h2co3.org"
license       = "BSD"
readme        = "README.md"
documentation = "https://h2co3.github.io/"
description   = "The Painless High-Level Persistence Engine"

[dependencies]
regex = "0.2.1"
clap  = "2.23.3"
