//
// sqiropt.rs
// The PHiLe Compiler
//
// Created by Arpad Goretity (H2CO3)
// on 07/04/2017
//

//! This module provides facilities for optimizing PHiLe programs in SQIR format.

use sqir::*;


/// Performs optimizations on naively-generated SQIR (as emitted by SQIRGen).
///
/// # Arguments:
///
/// * `sqir`: naive SQIR, likely generated by SQIRGen.
///
/// # Return value:
///
/// Optimized SQIR.
pub fn optimize_sqir(sqir: Sqir) -> Sqir {
    // trivial optimization: NOP
    sqir
}
